### ISSUE TITLE
devtools::install_github("halpo/parser") fatal error: R_ext/rlocale.h: No such file or directory

### ISSUE THREAD

**Issue by AndreMikulec** [halpo/parser#9]
When I do 
  devtools::install_github("halpo/parser")

I get this error.
  gram.y:248:28: fatal error: R_ext/rlocale.h: No such file or directory
How do I install?
What ENVIRONMENT variables do I need to setup.

I know I can get the R language source code from here.
  https://github.com/wch/r-source/blob/b156e3a711967f58131e23c1b1dc1ea90e2f0c43/src/include/rlocale.h

Thank you.
Andre Mikulec
Andre_Mikulec@Hotmail.com

**Comment by halpo** [comment]
Parser is defunct the functionality that it provided is now built into core R through the [getParseData](http://www.rdocumentation.org/packages/utils/functions/getParseData) function.  Use that instead.  If you tell me what you needed I might be able to help you find a solution.
